from __future__ import annotations

from typing import Any

# Curated high-signal cipher suite metadata for scanner posture analysis.
CIPHER_SUITE_DATABASE: dict[str, dict[str, Any]] = {
    "TLS_AES_128_GCM_SHA256": {
        "tls_family": "tls1.3",
        "key_exchange": "(EC)DHE",
        "authentication": "certificate-signature",
        "bulk_cipher": "AES-128",
        "mode": "GCM",
        "hash": "SHA256",
        "aead": True,
        "forward_secrecy": True,
        "pqc_signal": False,
        "security_level": "strong",
    },
    "TLS_AES_256_GCM_SHA384": {
        "tls_family": "tls1.3",
        "key_exchange": "(EC)DHE",
        "authentication": "certificate-signature",
        "bulk_cipher": "AES-256",
        "mode": "GCM",
        "hash": "SHA384",
        "aead": True,
        "forward_secrecy": True,
        "pqc_signal": False,
        "security_level": "strong",
    },
    "TLS_CHACHA20_POLY1305_SHA256": {
        "tls_family": "tls1.3",
        "key_exchange": "(EC)DHE",
        "authentication": "certificate-signature",
        "bulk_cipher": "CHACHA20",
        "mode": "POLY1305",
        "hash": "SHA256",
        "aead": True,
        "forward_secrecy": True,
        "pqc_signal": False,
        "security_level": "strong",
    },
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256": {
        "tls_family": "tls1.2",
        "key_exchange": "ECDHE",
        "authentication": "RSA",
        "bulk_cipher": "AES-128",
        "mode": "GCM",
        "hash": "SHA256",
        "aead": True,
        "forward_secrecy": True,
        "pqc_signal": False,
        "security_level": "acceptable",
    },
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384": {
        "tls_family": "tls1.2",
        "key_exchange": "ECDHE",
        "authentication": "RSA",
        "bulk_cipher": "AES-256",
        "mode": "GCM",
        "hash": "SHA384",
        "aead": True,
        "forward_secrecy": True,
        "pqc_signal": False,
        "security_level": "acceptable",
    },
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256": {
        "tls_family": "tls1.2",
        "key_exchange": "ECDHE",
        "authentication": "ECDSA",
        "bulk_cipher": "AES-128",
        "mode": "GCM",
        "hash": "SHA256",
        "aead": True,
        "forward_secrecy": True,
        "pqc_signal": False,
        "security_level": "acceptable",
    },
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384": {
        "tls_family": "tls1.2",
        "key_exchange": "ECDHE",
        "authentication": "ECDSA",
        "bulk_cipher": "AES-256",
        "mode": "GCM",
        "hash": "SHA384",
        "aead": True,
        "forward_secrecy": True,
        "pqc_signal": False,
        "security_level": "acceptable",
    },
    "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256": {
        "tls_family": "tls1.2",
        "key_exchange": "ECDHE",
        "authentication": "RSA",
        "bulk_cipher": "CHACHA20",
        "mode": "POLY1305",
        "hash": "SHA256",
        "aead": True,
        "forward_secrecy": True,
        "pqc_signal": False,
        "security_level": "acceptable",
    },
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256": {
        "tls_family": "tls1.2",
        "key_exchange": "ECDHE",
        "authentication": "ECDSA",
        "bulk_cipher": "CHACHA20",
        "mode": "POLY1305",
        "hash": "SHA256",
        "aead": True,
        "forward_secrecy": True,
        "pqc_signal": False,
        "security_level": "acceptable",
    },
    "TLS_RSA_WITH_AES_128_GCM_SHA256": {
        "tls_family": "tls1.2",
        "key_exchange": "RSA",
        "authentication": "RSA",
        "bulk_cipher": "AES-128",
        "mode": "GCM",
        "hash": "SHA256",
        "aead": True,
        "forward_secrecy": False,
        "pqc_signal": False,
        "security_level": "weak",
    },
    "TLS_RSA_WITH_AES_256_GCM_SHA384": {
        "tls_family": "tls1.2",
        "key_exchange": "RSA",
        "authentication": "RSA",
        "bulk_cipher": "AES-256",
        "mode": "GCM",
        "hash": "SHA384",
        "aead": True,
        "forward_secrecy": False,
        "pqc_signal": False,
        "security_level": "weak",
    },
    "TLS_RSA_WITH_3DES_EDE_CBC_SHA": {
        "tls_family": "tls1.2",
        "key_exchange": "RSA",
        "authentication": "RSA",
        "bulk_cipher": "3DES",
        "mode": "CBC",
        "hash": "SHA1",
        "aead": False,
        "forward_secrecy": False,
        "pqc_signal": False,
        "security_level": "legacy",
    },
    "TLS_X25519_MLKEM768_AES_256_GCM_SHA384": {
        "tls_family": "hybrid",
        "key_exchange": "X25519+ML-KEM-768",
        "authentication": "certificate-signature",
        "bulk_cipher": "AES-256",
        "mode": "GCM",
        "hash": "SHA384",
        "aead": True,
        "forward_secrecy": True,
        "pqc_signal": True,
        "security_level": "pqc-capable",
    },
    "TLS_X25519_KYBER768_DRAFT00_AES_256_GCM_SHA384": {
        "tls_family": "hybrid",
        "key_exchange": "X25519+KYBER768",
        "authentication": "certificate-signature",
        "bulk_cipher": "AES-256",
        "mode": "GCM",
        "hash": "SHA384",
        "aead": True,
        "forward_secrecy": True,
        "pqc_signal": True,
        "security_level": "pqc-capable",
    },
}

TLS13_CIPHER_SUITES = [
    "TLS_AES_128_GCM_SHA256",
    "TLS_AES_256_GCM_SHA384",
    "TLS_CHACHA20_POLY1305_SHA256",
]


def get_cipher_metadata(cipher_suite: str | None) -> dict[str, Any]:
    suite = str(cipher_suite or "").strip().upper()
    if not suite:
        return {
            "tls_family": "unknown",
            "key_exchange": "unknown",
            "authentication": "unknown",
            "bulk_cipher": "unknown",
            "mode": "unknown",
            "hash": "unknown",
            "aead": False,
            "forward_secrecy": False,
            "pqc_signal": False,
            "security_level": "unknown",
        }
    if suite in CIPHER_SUITE_DATABASE:
        return dict(CIPHER_SUITE_DATABASE[suite])
    return {
        "tls_family": "unknown",
        "key_exchange": "unknown",
        "authentication": "unknown",
        "bulk_cipher": "unknown",
        "mode": "unknown",
        "hash": "unknown",
        "aead": "GCM" in suite or "CHACHA20" in suite or "POLY1305" in suite,
        "forward_secrecy": any(x in suite for x in ("ECDHE", "DHE", "X25519", "X448")),
        "pqc_signal": any(x in suite for x in ("MLKEM", "ML-KEM", "KYBER")),
        "security_level": "unknown",
    }
